- name: Create dir for Metropolis Apps
  file:
    path: "{{ metropolis_apps_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
  tags: _metropolis_apps_download

- name: Download Metropolis Apps
  shell: /opt/ngc-cli/ngc registry resource download-version {{ item }}
  args:
    chdir: "{{ metropolis_apps_dir }}"
  with_items:
    - "{{ metropolis_apps_ngc_path }}"
    - "{{ metropolis_apps_data_ngc_path }}"
  become_user: "{{ ansible_user }}"
  tags: _metropolis_apps_download

# extract the downloaded files
- name: Extract Metropolis Apps [1]
  shell: |
    cd "{{ metropolis_apps_dir }}"
    cd metropolis-apps-standalone*
    tar -xvf metropolis-apps-standalone*.tar.gz
    mv standalone-deployment "{{ metropolis_apps_dir }}/"
    sudo chown -R "{{ ansible_user }}":"{{ ansible_user }}" "{{ metropolis_apps_dir }}/standalone-deployment"
  tags: _mqs_extract

# extract the downloaded files
- name: Extract Metropolis Apps [2]
  shell: |
    cd "{{ metropolis_apps_dir }}"
    cd metropolis-apps-sample-input-data*
    tar -xvf metropolis-apps-data*.tar.gz
    mv metropolis-apps-data "{{ metropolis_apps_dir }}/"
    sudo chown -R "{{ ansible_user }}":"{{ ansible_user }}" "{{ metropolis_apps_dir }}/metropolis-apps-data"
  tags: _mqs_extract
#
# Occupancy Analytics
# https://developer.nvidia.com/docs/mdx/dev-guide/text/MDX_People_Analytics_App.html#deploy

# edit the metropolis apps init file
- name: Edit Metropolis Apps env file
  ini_file:
    dest: "{{ metropolis_apps_dir }}/standalone-deployment/docker-compose/foundational/.env"
    section: ""
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {
        option: "MDX_SAMPLE_APPS_DIR",
        value: '"{{ metropolis_apps_dir }}/standalone-deployment/docker-compose"',
      }
    - {
        option: "MDX_DATA_DIR",
        value: '"{{ metropolis_apps_dir }}/metropolis-apps-data"',
      }
    - { option: "HOST_IP", value: '"0.0.0.0"' }
  tags: _mqs_occupancy_env
