# change ssh port to custom value

- name: Set SSH port to {{ ssh_port }}
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port {{ item }}"
    state: present
    mode: 0644
  with_items:
    - "22"
    - "{{ ssh_port }}"

- name: Create ufw profile for the custom ssh port
  template: src=custom_ssh.ufwprofile
    dest=/etc/ufw/applications.d/custom_ssh
    mode=644

- name: Allow incoming connections to the custom ssh port
  ufw: rule=allow name=custom_ssh

- name: Restart sshd
  service: name=sshd state=restarted

- name: Make Ansible to use new ssh port
  set_fact:
    ansible_port: "{{ ssh_port }}"
