# set ubuntu user password to "ubuntu"
# this is supposed to change with userdata

- name: Create password hash
  shell: python3 -c "import crypt; print(crypt.crypt('{{ system_user_password }}'))"
  register: system_user_password_hash

- name: Set password for "{{ ansible_user }}" user
  user:
    name: "{{ ansible_user }}"
    password: "{{ system_user_password_hash.stdout }}"
