# region copyright
# Copyright 2023-2024 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

- name: Create directory for Isaac Lab
  file:
    path: "{{ isaaclab_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Upload Isaac Lab setup files [1]
  template: src={{ item }}
    dest="{{ isaaclab_dir }}/{{ item }}"
    mode=755
    owner=ubuntu
    group=ubuntu
  with_items:
    - isaaclab.dockerfile

- name: Upload Isaac Lab setup files [2]
  template: src="{{ item }}"
    dest="/home/{{ ansible_user }}/Desktop"
    mode=755
    owner=ubuntu
    group=ubuntu
  with_items:
    - isaaclab.sh

# !!!TMP!!!
# remove once Isaac Lab is public
- name: "[TMP] Make sure {{ uploads_dir }} exists"
  file:
    path: "{{ uploads_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
#
- name: "[TMP] Upload isaaclab.pem"
  copy: src="{{ item }}"
    dest="{{ uploads_dir }}/{{ item }}"
    mode=0644
    owner=ubuntu
    group=ubuntu
  with_items:
    - isaaclab.pem

- name: Desktop icon for Isaac Lab
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/Desktop/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - isaaclab.desktop

- name: Allow execution of desktop icon for Isaac Lab
  shell: gio set "/home/{{ ansible_user }}/Desktop/{{ item }}" metadata::trusted true
  become_user: "{{ ansible_user }}"
  with_items:
    - isaaclab.desktop

- name: Set permissions for Isaac Lab desktop icon
  file:
    path: "/home/{{ ansible_user }}/Desktop/{{ item }}"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - isaaclab.desktop

# !!!TMP!!!
# remove once Isaac Lab is public
- name: "[TMP] Copy {{ uploads_dir }}/isaaclab.pem -> {{ isaaclab_dir }}"
  copy:
    src: "{{ uploads_dir }}/isaaclab.pem"
    dest: "{{ isaaclab_dir }}/isaaclab.pem"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    remote_src: yes

- name: Build Isaac Lab
  shell: docker build -t isaaclab -f "{{ isaaclab_dir }}/isaaclab.dockerfile" "{{ isaaclab_dir }}"
  become_user: "{{ ansible_user }}"
  tags:
    - skip_in_ovami
