name: Build App Docker

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-docker.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-docker.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout code
        run: |
          git clone https://github.com/${{ toLower(github.repository) }} .
          git checkout ${{ github.sha }}

      - name: Build docker image
        run: |
          cd ${{ github.workspace }}
          echo "FROM ubuntu:latest" > Dockerfile
          docker build -t ghcr.io/${{ toLower(github.repository) }}/app-image:latest .

      - name: Login to GH registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ toLower(github.repository)_owner }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ toLower(github.repository) }}/app-image:latest
